{
    "name": "Petty Cash",
    "version": "18.0.1.9.0",
    "category": "Autozone/Accounting",
    "author": "Autozone",
    "summary": "ทะเบียนคุมเงินสดย่อยรายสาขา: ใบเบิก/ใบเคลียร์/ขอเติมเงิน "
    "สร้าง draft vendor bill พร้อม analytic สาขาให้ฝ่ายบัญชีตรวจและ post เอง",
    "depends": ["accountant", "autozone_base_address", "l10n_th_account_tax"],
    "data": [
        "security/petty_cash_groups.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/partner_data.xml",
        "views/petty_cash_fund_views.xml",
        "views/petty_cash_request_views.xml",
        "views/petty_cash_clearing_views.xml",
        "views/petty_cash_replenish_views.xml",
        "views/petty_cash_count_views.xml",
        "views/menus.xml",
        "report/petty_cash_reports.xml",
        "report/report_request.xml",
        "report/report_clearing.xml",
        "report/report_replenish.xml",
        "report/report_count.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
