from odoo import fields, models


class ResGroups(models.Model):
    """เพิ่ม marker เพื่อให้รู้ว่ากลุ่มไหน generate โดย Role Builder และ sync/ลบได้ปลอดภัย"""
    _inherit = "res.groups"

    arb_generated = fields.Boolean(string="Generated by Role Builder", default=False, index=True)
    arb_key = fields.Char(string="Builder Key", index=True)
    arb_kind = fields.Selection(
        [("role", "Role"), ("brick", "Capability"), ("foundation", "Foundation")],
        string="Builder Kind",
    )


class IrModelAccess(models.Model):
    _inherit = "ir.model.access"

    arb_generated = fields.Boolean(string="Generated by Role Builder", default=False, index=True)
    arb_key = fields.Char(string="Builder Key", index=True)


class IrRule(models.Model):
    _inherit = "ir.rule"

    arb_generated = fields.Boolean(string="Generated by Role Builder", default=False, index=True)
    arb_key = fields.Char(string="Builder Key", index=True)


class IrUiMenu(models.Model):
    _inherit = "ir.ui.menu"

    arb_generated = fields.Boolean(string="Generated by Role Builder", default=False, index=True)
    arb_key = fields.Char(string="Builder Key", index=True)


class IrActionsActWindow(models.Model):
    _inherit = "ir.actions.act_window"

    arb_generated = fields.Boolean(string="Generated by Role Builder", default=False, index=True)
    arb_key = fields.Char(string="Builder Key", index=True)
